---
name: Reflexio Base Rules
trigger: always
version: 1.0
description: >
  Базовые правила поведения для Reflexio 24/7 в Cursor IDE.
  Определяют стандарты разработки, безопасности и автоматизации.

rules:
  - "Все playbook'и должны иметь раздел parameters с описанием параметров."
  
  - "Audit Pack нельзя запускать без проверки зависимостей (pyproject.toml, requirements.txt)."
  
  - "Каждая метрика должна иметь документированную единицу измерения."
  
  - "При работе с аудиофайлами всегда проверять ZERO_RETENTION и PII_MASK настройки."
  
  - "Все изменения в API endpoints должны сопровождаться обновлением документации."
  
  - "Digest генератор должен проверять наличие транскрипций перед анализом."
  
  - "Edge listener должен логировать все отфильтрованные сегменты (не-речь)."
  
  - "При ошибках ASR транскрипции должен сохраняться оригинальный файл для повторной обработки."
  
  - "Все скрипты в scripts/ должны иметь обработку ошибок и логирование."
  
  - "Memory Bank должен обновляться при значительных архитектурных изменениях."

validation:
  - "Проверять наличие .env.example при изменении .env"
  - "Проверять соответствие pyproject.toml актуальным зависимостям"
  - "Проверять наличие тестов для новых API endpoints"

security:
  - "Никогда не коммитить .env файлы"
  - "Проверять PII-маскирование перед сохранением транскрипций"
  - "Валидировать входные аудиофайлы (размер, формат)"













